### ISSUE TITLE
Plans for a new default site.

### ISSUE THREAD

**Issue by Gamerappa** [ChazizYT/IEChaziz#3]
Currently. After opening the application. It'll show google.com.
I have plans to do a Frontpagey site so it can be the page you see after you open Codename NetChaziz.

_**It should be made with 2003, Yes I know Chaziz has a copy of Office XP but that's a rebranded version of Office 2000.**_

It'll replace the "Url" value of WebBrowser1. which is currently set to "google.com".

`Me.WebBrowser1.Url = New System.Uri("http://google.com", System.UriKind.Absolute)`

Could be included on a future beta 1.x release.

**Comment by PF94** [comment]
This was some weird 2003page foreshadowing, 5 months before it launched. How.
